services:
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

  drone:
    build:
      context: ./drone
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
